version: '3.8'
services:
  mysql:
    container_name: nadzor_mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mysql/data/:/var/lib/mysql:rw
      - ./.docker/mysql/log/:/var/log/mysql:rw
      - ./.docker/mysql/config/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
  apache:
    container_name: nadzor_apache
    build: ./.docker/apache
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html/public:rw
      - ./.docker/apache/config/vhosts.conf:/etc/apache2/sites-enabled/vhosts.conf:ro
    depends_on:
      - php
  php:
    container_name: nadzor_php
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    environment:
      APP_ENV: ${APP_ENV}
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
    volumes:
      - .:/var/www/html:rw
      - ./.docker/php/logs:/app/var/logs:rw
    depends_on:
      - mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: nadzor_phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8082:80"