# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    router.request_context.host: webnadzor.net
    router.request_context.scheme: https
    icon_directory: 'assets/images/details_icons'
    icon_directory_full_path: '%kernel.project_dir%/public/%icon_directory%'
    map_marker_directory: 'assets/images/map-icon'
    map_marker_directory_full_path: '%kernel.project_dir%/public/%map_marker_directory%'
    logo_directory: 'assets/images/logo'
    logo_directory_full_path: '%kernel.project_dir%/public/%logo_directory%'
    client_storage_directory: 'assets/images/client-storage'
    client_storage_directory_full_path: '%kernel.project_dir%/public/%client_storage_directory%'
    xml_directory: '%kernel.project_dir%/data'
    archive_directory: '%kernel.project_dir%/archive'
    database_username: '%env(DATABASE_NAME)%'
    database_password: '%env(DATABASE_PASSWORD)%'
    images_directory: '/uploads/images/client_images/'
    device_document_directory: 'uploads/device-document'
    device_document_directory_full_path: '%kernel.project_dir%/public/%device_document_directory%'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $mapMarkerDirectory: '%map_marker_directory%'
            $mapMarkerFullPathDirectory: '%map_marker_directory_full_path%'
            $xmlDirectory: '%xml_directory%'
            $archiveDirectory: '%archive_directory%'
            $iconDirectory: '%icon_directory%'
            $clientStorageDirectory: '%client_storage_directory_full_path%'
            $iconFullDirectory: '%icon_directory_full_path%'
            $deviceDocumentDirectory: '%device_document_directory%'

    _instanceof:
        App\Service\Alarm\AlarmHandlerInterface:
            tags: [ 'app.alarm.validator' ]
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Monolog\Processor\PsrLogMessageProcessor:
        tags: { name: monolog.processor, handler: sentry }

    App\Service\Alarm\ValidatorCollection:
        arguments:
            $validators: !tagged_iterator app.alarm.validator

    ### File uploader target path
    App\Service\FileUploader\Types\ClientStorageImageUploader:
        $targetDirectory: '%client_storage_directory_full_path%'

    App\Service\FileUploader\Types\MapMarkerIconUploader:
        $targetDirectory: '%map_marker_directory_full_path%'

    App\Service\FileUploader\Types\ImageUploader:
        $targetDirectory: '%icon_directory_full_path%'

    App\Service\FileUploader\Types\LogoUploader:
        $targetDirectory: '%logo_directory_full_path%'

    App\Service\FileUploader\Types\DeviceDocumentUploader:
        $targetDirectory: '%device_document_directory_full_path%'